### ISSUE TITLE
Make the command prefix changeable

### ISSUE THREAD

**Issue by ArtOfCode-** [ProgramFOX/SE-Chatbot#24]
The command prefix, currently `>>`, is embedded into the core code in miles of regex and in various places. To avoid issues with multiple bots in a room, it should be changeable.

**Comment by overactor** [comment]
@ProgramFOX Should this be configurable in Config.py?

**Comment by ArtOfCode-** [comment]
@overactor Yes it should - it's not going to need to change in operation so a persistent config value sounds fine to me.

**Comment by ProgramFOX** [comment]
Yes, in Config.py sounds fine.

**Comment by du76gvtrHG** [comment]
@ArtOfCode- You kicked me many times from all over StackExchange since 2011 especially from the JS room but I'm not going away before ironing out my skills or being given another opportunity to show I'm not the one who started the problem.
